# ?????? ??? ?????? ????? ?????????
spring.profiles.active=prod
  # ??? dev ????? ????? ????????? ????????

# ???????? ????????? ??????????? ?????????????
logging.level.org.springframework.jdbc.datasource.init=DEBUG

spring.web.resources.static-locations=classpath:/static/