# H2 Database for tests (??????????? ? PostgreSQL ?????)
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ????????? ??????????? ??? ??????
logging.level.com.example.usefy=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# H2 console (???????????, ??? ???????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ????????? ???????????? data-test.sql ??? ??????
spring.sql.init.data-locations=classpath:data-test.sql